// DO NOT EDIT. This file is automatically generated.
// This file SHOULD be checked into source version control.
// This file is automatically updated when running `dev.ts`.

import { TelevisionMediaService } from "../tv.ts";
import $0 from "./witcher.tsx";

export const TV = new TelevisionMediaService({
  "witcher": $0
});
