// DO NOT EDIT. This file is automatically generated.
// This file SHOULD be checked into source version control.
// This file is automatically updated when running `dev.ts`.

import { TelevisionMediaService } from "../tv.ts";
import $0 from "./lazarus-project.tsx";
import $1 from "./witcher.tsx";
import $2 from "./last-kingdom.tsx";

export const TV = new TelevisionMediaService({
  "lazarus-project": $0,
  "witcher": $1,
  "last-kingdom": $2
});
