#!/usr/bin/env -S deno run -A --watch=static/,routes/

import dev from "$fresh/dev.ts";
import { basename } from "https://deno.land/std@0.188.0/path/mod.ts";
import { DATA_DIR } from "./constants.ts";
import { glob } from "https://deno.land/x/handy@0.4.0/fs/glob.ts";
import { MediaType } from "./data/media.ts";

async function createIndexFile(mediaType: MediaType) {
  const dir = `${DATA_DIR}/${mediaType}`;
  const entities = await glob(`${dir}/*.tsx`);

  const filePath = `${DATA_DIR}/${mediaType}/index.ts`;
  const exportName = mediaType.toUpperCase() + "S";

  const mediaService = "MediaService";

  const mediaServiceFile = "media.ts";

  const fileText = `
// DO NOT EDIT. This file is automatically generated.
// This file SHOULD be checked into source version control.
// This file is automatically updated when running \`dev.ts\`.

import { ${mediaService} } from "../${mediaServiceFile}"
${
    entities
      .map((entity, i) => `import $${i} from "./${basename(entity)}";`)
      .join("\n")
  }

export const ${exportName} = new ${mediaService}({
${
    entities
      .map((entity, i) => `  "${basename(entity, ".tsx")}": $${i}`)
      .join(",\n")
  }
})
`.trimStart();

  await Deno.writeTextFile(filePath, fileText);
}

await createIndexFile("post");
await createIndexFile("book");
await createIndexFile("game");
await createIndexFile("film");

await dev(import.meta.url, "./main.ts");
