// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about/design.tsx";
import * as $1 from "./routes/about/me.tsx";
import * as $2 from "./routes/about/site.tsx";
import * as $3 from "./routes/contact.tsx";
import * as $4 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/about/design.tsx": $0,
    "./routes/about/me.tsx": $1,
    "./routes/about/site.tsx": $2,
    "./routes/contact.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
