// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about/design.tsx";
import * as $1 from "./routes/about/index.tsx";
import * as $2 from "./routes/about/me.tsx";
import * as $3 from "./routes/about/ratings.tsx";
import * as $4 from "./routes/books.tsx";
import * as $5 from "./routes/contact.tsx";
import * as $6 from "./routes/film/[slug].tsx";
import * as $7 from "./routes/films.tsx";
import * as $8 from "./routes/game/[slug].tsx";
import * as $9 from "./routes/games.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/music.tsx";
import * as $12 from "./routes/post/[slug].tsx";
import * as $13 from "./routes/posts.tsx";
import * as $14 from "./routes/reviews.tsx";
import * as $15 from "./routes/tag/[name].tsx";
import * as $16 from "./routes/tv.tsx";

const manifest = {
  routes: {
    "./routes/about/design.tsx": $0,
    "./routes/about/index.tsx": $1,
    "./routes/about/me.tsx": $2,
    "./routes/about/ratings.tsx": $3,
    "./routes/books.tsx": $4,
    "./routes/contact.tsx": $5,
    "./routes/film/[slug].tsx": $6,
    "./routes/films.tsx": $7,
    "./routes/game/[slug].tsx": $8,
    "./routes/games.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/music.tsx": $11,
    "./routes/post/[slug].tsx": $12,
    "./routes/posts.tsx": $13,
    "./routes/reviews.tsx": $14,
    "./routes/tag/[name].tsx": $15,
    "./routes/tv.tsx": $16,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
