// DO NOT EDIT. This file is automatically generated.
// This file SHOULD be checked into source version control.
// This file is automatically updated when running `dev.ts`.

import $0 from "./about-this-site.tsx";
import $1 from "./all-in-on-deno.tsx";
import $2 from "./anti-clutter.tsx";
import $3 from "./ratings-systems.tsx";
import $4 from "./the-hard-problems.tsx";
import $5 from "./tiers.tsx";
import { MediaService } from "/lib/media.ts";

export const POSTS = new MediaService({
  "about-this-site": $0,
  "all-in-on-deno": $1,
  "anti-clutter": $2,
  "ratings-systems": $3,
  "the-hard-problems": $4,
  "tiers": $5,
});
