// DO NOT EDIT. This file is automatically generated.
// This file SHOULD be checked into source version control.
// This file is automatically updated when running `dev.ts`.

import { MediaService } from "../../lib/media.ts";
import $0 from "./ratings-systems.tsx";
import $1 from "./about-this-site.tsx";
import $2 from "./all-in-on-deno.tsx";
import $3 from "./tiers.tsx";
import $4 from "./the-hard-problems.tsx";

export const POSTS = new MediaService({
  "ratings-systems": $0,
  "about-this-site": $1,
  "all-in-on-deno": $2,
  "tiers": $3,
  "the-hard-problems": $4
});
