// DO NOT EDIT. This file is automatically generated.
// This file SHOULD be checked into source version control.
// This file is automatically updated when running `dev.ts`.

import { MediaService } from "../media.ts";
import $0 from "./ratings-systems.tsx";
import $1 from "./about-this-site.tsx";
import $2 from "./the-hard-problems.tsx";

export const POSTS = new MediaService({
  "ratings-systems": $0,
  "about-this-site": $1,
  "the-hard-problems": $2
});
