// DO NOT EDIT. This file is automatically generated.
// This file SHOULD be checked into source version control.
// This file is automatically updated when running `dev.ts`.

import { MusicMediaService } from "../music.ts";
import $0 from "./built-to-spill.tsx";
import $1 from "./haim.tsx";

export const ARTISTS = new MusicMediaService({
  "built-to-spill": $0,
  "haim": $1
});
