// DO NOT EDIT. This file is automatically generated.
// This file SHOULD be checked into source version control.
// This file is automatically updated when running `dev.ts`.

import { MediaService } from "../media.ts"
import $0 from "./midsommar.tsx";
import $1 from "./mother.tsx";
import $2 from "./the-day-after.tsx";
import $3 from "./cargo.tsx";
import $4 from "./martyrs.tsx";
import $5 from "./world-war-z.tsx";

export const FILMS = new MediaService({
  "midsommar": $0,
  "mother": $1,
  "the-day-after": $2,
  "cargo": $3,
  "martyrs": $4,
  "world-war-z": $5
})
