// DO NOT EDIT. This file is automatically generated.
// This file SHOULD be checked into source version control.
// This file is automatically updated when running `dev.ts`.

import { MediaService } from "../media.ts";


export const BOOKS = new MediaService({

});
